version: 2.1

parameters:
  trigger:
    type: string
    default: default

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  default:
    executor: default
    steps:
      - run: echo "base job!!"
  build-verification:
    executor: default
    steps:
      - run: echo "run build-verification"
  sonarqube:
    executor: default
    steps:
      - run: echo "run sonarqube"
  securityscan:
    executor: default
    steps:
      - run: echo "run securityscan"

workflows:
  base:
    when:
      equal: [ <<pipeline.parameters.trigger>>, default ]
    jobs:
      - default
      - build-verification
      - sonarqube
      - securityscan
