version: 2.1

parameters:
  env:
    type: enum
    enum: [dev, prod]
    default: dev

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  nightly:
    executor: default
    steps:
      - checkout
      - run: echo "nightly build"
  prja:
    executor: default
    steps:
      - checkout
      - run: echo "prja's pr and merge test"

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - nightly

  prja:
    jobs:
      - prja:
          filters:
            paths:
              only:
                - main
