version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  default:
    executor: default
    steps:
      - checkout
      - run: echo "default job!!"

workflows:
  when:
    equel: [<<pipeline.git.branch>>, main]
  default:
    jobs:
      - default
