version: 2.1

setup: << pipeline.parameters.run-setup >>

orbs:
  continuation: circleci/continuation@1.0.0
  path-filtering: circleci/path-filtering@1.1.0

parameters:
  trigger:
    type: enum
    enum: [ default,
            sonar, test, core, portal, deployment, cost, action, validator,
            svc, cmdb, wasm, widp, base, echo, prometheus-bundle-image,
            istio, kiali, bazel, lambda ]
    default: default
  env:
    type: enum
    enum: [dev, prod]
    default: dev

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  check-run-setup:
    executor: default
    steps:
      - run: echo "run check-run-setup"
  build-verification:
    executor: default
    steps:
        - run: echo "run build-verification"
  sonarqube:
    executor: default
    steps:
      - run: echo "run sonarqube"
  securityscan:
    executor: default
    steps:
      - run: echo "run securityscan"


workflows:
  main:
    jobs:
      - check-run-setup
      # - continuation/continue:
      #     configuration_path: .circleci/base.yml
      #     parameters: |
      #       {
      #         "trigger": "<<pipeline.parameters.trigger>>"
      #       }
      # - path-filtering/filter:
      #     base-revision: main
      #     mapping: |
      #       prja/.* env "dev" prja/.circleci/config.yml
