version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  default:
    executor: default
    steps:
      - checkout
      - run: echo "main default job!!"

workflows:
  default:
    when:
      equals: [ <<pipeline.git.branch>>, main ]
    jobs:
      - default
      - continuation/continue:
          configuration_path: .circleci/default.yml
